### ISSUE TITLE
Jekyll interpolation

### ISSUE THREAD

**Issue by ilionic** [atstp/annotater#1]
How Jekyl front matter would look like to replicate following example?

```
annotater([{
    name: /wget|curl/,
    tooltip: "windows users might want to use<br>Invoke-RestMethod instead of {name}"
}])
```

as this one doesn't work.

```
      annotater:
        -
           name: /wget|curl/
           tooltip: "windows users might want to use<br>Invoke-RestMethod instead of {name}"

```
